encoding: utf-8
title: Templates-Master docs
email: support@templates-master.com
description: > # this means to ignore newlines until "baseurl:"
  Templates-Master extensions, themes and development documentation
baseurl: ""
url: "http://tmhub.github.io"

exclude:
  - bower_components/lunr.js/example/
  - bower_components/lunr.js/lib/
  - bower_components/lunr.js/test/
  - bower_components/material-design-lite/src/
  - bower_components/material-design-lite/utils/
  - bower_components/mustache/bin/
  - bower_components/mustache/hooks/
  - bower_components/mustache/spec/
  - bower_components/mustache/wrappers/
  - bower_components/prism/examples/
  - bower_components/prism/plugins/
  - bower_components/prism/tests/
  - bower_components/prism/vendor/

github:
  repository_url: https://github.com/tmhub/tmhub.github.io

prose:
  siteurl: "http://tmhub.github.io/"
  media: "media"
  ignore:
    - .gitignore
    - bower.json
    - _config.yml
    - search.json
    - /_includes
    - /_layouts
    - /_posts
    - /bower_components

# Outputting
permalink: pretty

# Build settings
safe: true
lsi: false
# highlighter: pygments

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  # syntax_highlighter: pygments
  enable_coderay: false

# markdown: redcarpet
# redcarpet:
#   extensions:
#     - no_intra_emphasis
#     - tables
#     - fenced_code_blocks
#     - autolink
#     - strikethrough
#     - superscript
#     - with_toc_data
