- title: Extensions
  items:
    - title: Cache
      url: /extensions/cache/

    - title: Configurable Swatches
      url: /extensions/catalog-configurable-swatches/
      free: 1

    - title: Crawler
      url: /extensions/crawler/

    - title: EasyCatalogImages
      url: /extensions/easycatalogimages/
      free: 1

    - title: Email
      url: /extensions/email/

    - title: Firecheckout
      url: /extensions/firecheckout/

    - title: Navigation Pro
      url: /extensions/navigationpro/

    - title: Order Attachments
      url: /extensions/order-attachments/

    - title: Testimonials
      url: /extensions/testimonials/
      free: 1

    - title: Rich Snippets
      url: /extensions/richsnippets/

- title: Argento themes
  url: /argento/
  items:
    # - title: Argento Argento
    #   url: /argento/argento/
    #   column: 1

    - title: Argento Flat
      url: /argento/flat/
      column: 2

    # - title: Argento Mall
    #   url: /argento/mall/
    #   column: 3

    # - title: Argento Pure
    #   url: /argento/pure/
    #   column: 4

    - title: Argento Pure 2
      url: /argento/pure2/
      column: 4

- title: Themes
  items:
    - title: Absolute Theme
      url: /themes/f001-absolute/
      free: 1

    - title: Classic Theme
      url: /themes/f002-classic/
      free: 1

    - title: Mobile Star Theme
      url: /themes/m001-mobile-star/
