- title: Extensions
  items:
    - title: Configurable Swatches
      url: /catalog-configurable-swatches/
      column: 1
      free: 1

    - title: Crawler
      url: /crawler/
      column: 1

    - title: Firecheckout
      url: /firecheckout/
      column: 1

    - title: Order Attachments
      url: /order-attachments/
      column: 1

    - title: Testimonials
      url: /testimonials/
      column: 2

    - title: Rich Snippets
      url: /richsnippets/
      column: 2

- title: Argento themes
  url: /argento/
  items:
    - title: Argento Argento
      url: /argento/argento.html
      column: 1

    - title: Argento Flat
      url: /argento/flat.html
      column: 2

    - title: Argento Mall
      url: /argento/mall.html
      column: 3

    - title: Argento Pure
      url: /argento/pure.html
      column: 4

- title: Themes
  items:
    - title: Absolute Theme
      url: /f001-absolute-theme/
      column: 1
      free: 1

    - title: Classic Theme
      url: /f002-classic-theme/
      column: 2
      free: 1
